### ISSUE TITLE
Bug: Scroll indicator behind player

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#1072]
When scrolling down in the episodes list of an podcast the scroll indicator disappears behind the player.

![image](https://github.com/Automattic/pocket-casts-ios/assets/27677748/d880357b-c315-49e4-8227-9c62e36f568d)

**Comment by rviljoen** [comment]
I think the problem lies here:

https://github.com/Automattic/pocket-casts-ios/blob/da0e130d8b11a77a3002ea69879fcb2ac9d7f069/podcasts/AddCustomViewController.swift#L251-L255

When setting up the content inset, we should do the same for the vertical scroll bar, i.e.:

`scrollView.verticalScrollIndicatorInsets = UIEdgeInsets(top: existingInset.top, left: existingInset.left, bottom: existingInset.bottom + Constants.Values.miniPlayerOffset, right: existingInset.right)`

Also needs to be updated here:
https://github.com/Automattic/pocket-casts-ios/blob/da0e130d8b11a77a3002ea69879fcb2ac9d7f069/podcasts/PodcastViewController.swift#L338-L339
