### ISSUE TITLE
Embeded chapitered artwork in mp3 file not showed on bar and ios homescreen

### ISSUE THREAD

**Issue by ArnaudK69** [Automattic/pocket-casts-ios#1433]
### Description

Embeded chapitered artwork in imported mp3 file not showed on bar and ios homescreen.
In fullscreen played, no issues, see captures

### Step-by-step reproduction instructions

import chapitered mp3 on pocketcast
(exemple: https://podcast.ausha.co/total-trax/nos-annees-hong-kong-2-202401161028
click on download button )
(my theory: this podcast only put artwork on chapters, not on global mp3)
play :)

### Screenshots or screen recording

![IMG_0163](https://github.com/Automattic/pocket-casts-ios/assets/133022725/a59cc8fc-e56e-4607-a4a6-6a2e9f65ad4d)
![IMG_0164](https://github.com/Automattic/pocket-casts-ios/assets/133022725/11c60192-49ab-458f-b545-151da8a2ede9)
![IMG_0165](https://github.com/Automattic/pocket-casts-ios/assets/133022725/14b86e9e-6602-43bb-a183-4c41ba29793b)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

iPhone 15 Pro Max, last iOS, last Pocketcast

**Comment by rviljoen** [comment]
Hi @ArnaudK69 - I get a Cloudflare error when trying to access the sample MP3 file.

**Comment by ArnaudK69** [comment]
> Hi @ArnaudK69 - I get a Cloudflare error when trying to access the sample MP3 file.

hi i changed the link.

**Comment by rviljoen** [comment]
Hi @ArnaudK69 - your suspicion was correct. The file in question only has chapter artwork included, but no episode artwork:

![image](https://github.com/Automattic/pocket-casts-ios/assets/25402814/7fd30d85-092b-477b-b8cc-05f59218069c)

There's an [existing request](https://github.com/Automattic/pocket-casts-ios/issues/3) to add an option to the app to show chapter art on the lock and home screens, instead of episode art. Maybe you can add your request on that issue as well.
