### ISSUE TITLE
Long chapter title get truncated

### ISSUE THREAD

**Issue by BKrnk1337** [Automattic/pocket-casts-ios#1522]
I noticed that very long chapter names are cut off in the app. Here is an example:

![image](https://github.com/Automattic/pocket-casts-ios/assets/27677748/fb4c5300-f887-46f7-bfb2-5bd2f5b3db0d)

Link to the podcast episode:
https://pca.st/episode/3530a0f7-a4a5-4690-ba6b-2fe0a5fca725

**Comment by rviljoen** [comment]
The current implementation limits the description to 2 lines, which is why the ... show up at the end. Not sure if this was a conscious design choice at the time or a default setting in the interface builder. @leandroalonso can someone from the design team weigh in here? May be a quick fix while you are working on chapter selection.

For reference, Apple Podcasts does not truncate the chapters and I must say that I prefer that look:

![image](https://github.com/Automattic/pocket-casts-ios/assets/25402814/7d9e6f8b-25d2-4f95-8d85-b17fb22ad25e)

**Comment by leandroalonso** [comment]
@david-gonzalez-a8c any thoughts?

**Comment by david-gonzalez-a8c** [comment]
> @david-gonzalez-a8c any thoughts?

I favor using the entire title like in Apple Podcasts. Real estate in this screen, fully dedicated to chapters, is not that limited compared to others like the player, and I see the usefulness of being able to see the entire title.

**Comment by joashrajin** [comment]
cc @danielebogo

**Comment by danielebogo** [comment]
@joashrajin fixed and merged for 7.79
