### ISSUE TITLE
Apple Watch: no Wearable Logs Sent in Ticket

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#39]
User having trouble logging in to the Pocket Casts Watch app. They sent a ticket along with logs and no wearable logs were included.

### Cases

* 4629344-zen
* 4851559-zen
* 4858784-zen
* 4528819-zen
* 4528819-zen

**Comment by rviljoen** [comment]
I suspect the reason for not sending logs is that watch app is not open at the time when the support request is created. We use the `sendMessage(_:replyHandler:errorHandler:)` method and as per Apple documentation:

> Calling this method from your iOS app does not wake up the corresponding WatchKit extension. If you call this method and the counterpart is unreachable (or becomes unreachable before the message is delivered), the errorHandler block is executed with an appropriate error.
https://developer.apple.com/documentation/watchconnectivity/wcsession/1615687-sendmessage

I can simulate this error by keeping the watch app closed when creating a support request:
`2023-01-24 21:44:45.377704+0200 podcasts[4880:1272908] [WC] -[WCSession _onqueue_notifyOfMessageError:messageID:withErrorHandler:] (null) errorHandler: YES with WCErrorCodeNotReachable
Error: WatchConnectivity session on paired device is not reachable.`

We should probably add some text to inform the user of the need to open the watch app in order to retrieve the logs.

**Comment by joashrajin** [comment]
6310819-zd-woothemes

**Comment by igotdes** [comment]
User in #6310819-zen reported back. In the ticket, they shared a screenshot from the app (I'm not sure if it's okay to share here). It shows that there _are_ watch logs. However, they were not attached to the ticket they created, #6322351-zen.

As a workaround for this issue, would it be possible to make it so that the logs can be copied and pasted?
