### ISSUE TITLE
Siri Suggestions: artwork not appearing on lock screen while playing with Siri Suggestions

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#43]
A user reported that the artwork on the playback control is not appearing on the lock screen. According to the screenshot, it looks like the playback was initiated from Siri Suggestions.

> Thumbnails aren't loading in iOS's lock screen media control. This is with the latest iOS and Pocket Casts versions (non-beta):

On iOS 15.2 and app version 7.19.1.

<img src="https://user-images.githubusercontent.com/40906847/148329162-20d26c73-950f-44d8-9234-0dba03f0668e.png" width="300">

**Comment by thabotswana** [comment]
Another report in 5704082-zen

>1. Remove everything from the queue from the pocket casts
>2. Start playing any episode
>3. Lock the screen
>4. While on the lock screen, scroll to the end of the episode using
>widget
>
>As soon as episode stops playing, “now playing” widget will show
suggestions and you can observe the issue.


https://user-images.githubusercontent.com/35628116/201613621-f543a2ef-e9f1-456d-84d8-ae8cd9362d2d.mp4

**Comment by rviljoen** [comment]
I have tracked the issue down to this section of code:

https://github.com/Automattic/pocket-casts-ios/blob/6f51ce58b5150231e7bdb7b130b0fcec95f8d261/podcasts/SiriShortcutsManager.swift#L174-L176

It [seems like you](https://stackoverflow.com/questions/69292991/does-creating-an-inimage-from-a-url-work) have to init ```INImage``` with image data instead of an URL. 

The following hack resolved the problem:
```Swift
let data = try? Data(contentsOf: podcastUrl)
let podcastArtwork = INImage(imageData: data!)
```

However, doing a synchronise load of the image on the main thread triggers a warning. I think this could be a quick fix for someone with more knowledge of Swift concurrency and the Pocket Casts codebase. 

Below you can see the issue in the App Store build (red icon) and top right is fixed (black icon) using the code above.

![Image](https://user-images.githubusercontent.com/25402814/203647465-b9a45bbd-160c-480c-aa98-49e5e23a0609.png)
