### ISSUE TITLE
Share Links: links with position in them do not start from the shared position

### ISSUE THREAD

**Issue by pocketcasts** [Automattic/pocket-casts-ios#5]
### Steps to reproduce the behavior

1. Share a link with position from the app
2. Close the app and wipe the app's data
3. Open the link
4. Observe that the web player has the podcast loaded to the proper position
5. Tap the button to open the podcast in the app
6. Begin playing the podcast within the app and observe that it does not start playing from the proper position

### Additional information

<img src="https://user-images.githubusercontent.com/1119271/137055136-959b12ce-fc58-4313-8df3-3e2aa9c3d5a3.PNG" width="270" alt="IMG_5090"> <img src="https://user-images.githubusercontent.com/1119271/137055144-567f3255-925d-4155-ab3d-0aa4f8f34d63.PNG" width="270" alt="IMG_5091">

What currently happens is that a screen pops up with some options and when you tap the play button the episode card opens but with the timestamp set either to zero or to the last point you were listening at if you had previously been listening to that episode.

<img src="https://user-images.githubusercontent.com/1119271/137055155-096f9032-806f-4c54-8fc1-1bbfb1deefa4.PNG" width="270" alt="IMG_5094"> <img src="https://user-images.githubusercontent.com/1119271/137055158-7740f2e6-8bd9-4af2-b0a1-2bc9e7ea1093.PNG" width="270" alt="IMG_5095">

**Comment by ezebecke** [comment]
+1 at 5615543-zen

**Comment by rviljoen** [comment]
When creating a current position share link, the time is included as a parameter (t) in the URL, e.g.:
https://pca.st/oqydnhns#t=155.0

When the web page is rendered, the _"Open in Pocket Casts"_ button no longer includes the time:
<img src="https://user-images.githubusercontent.com/25402814/214618063-46db37ab-b715-4d23-8790-c8b5b3842c04.png" height="50%" width="50%"/>

So in order to support this, we'll need to update both the web page and the app to take the timestamp into consideration. The Android app has a similar issue logged: https://github.com/Automattic/pocket-casts-android/issues/21

**Comment by mdrockwell** [comment]
> In Pocket Casts for iOS, links created using the Share Link To Current Position will open the Pocket Casts app to the relevant episode, but it will not start playing to the intended position in the episode.
> 
> In Pocket Casts for Android, links will open in a web browser and play from the shared position. Is there any chance the iOS app could better handle those links?
> 
> I’d actually prefer if on iOS, it opened in a web browser. The current behavior defeats the purpose of sharing to “current position”.

https://forums.pocketcasts.com/forums/topic/bug-share-link-to-current-position-doesnt-seem-to-work-on-ios/?view=all#post-339

**Comment by joashrajin** [comment]
7787187-zd-a8c
