### ISSUE TITLE
Feature Request: More differentiated prioritization for the Add Up Next feature

### ISSUE THREAD

**Issue by loremipsum2022** [Automattic/pocket-casts-ios#543]
So far you can choose between two options in the Add Up Next Settings: Top or bottom. it would be great if you could assign a priority to each podcast (e.g. 1-10). Depending on the priority, new episodes would then be sorted into the queue.

**Comment by CookieyedCodes** [comment]
I personally would prefer a function that would allow the user to choose the location from where add to up next adds podcasts from (make it a swipe action next to the archive swipe) -add to up last will remain the same because that's logical & as the que moves through it eventually makes the que automatically add to top as you get through episodes, I want it to be be quickly changeable because it feels more intuitive in my opinion-

Too add to your idea tho I personally wouldn't mind an add oldest unarchived to upnext/uplast opinion &/or a add next episode to CustomNUM (should ignore pods allready added to upnext & obviously not enabled by default) but that should sync 😉(really all these options), I personally would prefer more control over arbitrary number rankings 🤔

**Comment by leandroalonso** [comment]
Heya @loremipsum2022! Thanks for your request, I'm closing this Issue because feature requests/ideas should go to our  [Discussions](https://github.com/Automattic/pocket-casts-ios/discussions) section!
