### ISSUE TITLE
Dark Contrast: Close Icon is fully white

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#552]
### Expected behavior

The X should be readable

### Actual behavior

The close icon is fully white

### Steps to reproduce the behavior

Set the theme to 'Dark Contrast'
Go to Profile > Settings > About

![IMG_3033](https://user-images.githubusercontent.com/16253818/204484102-34892f4f-a3d8-4156-81b4-84a83e9bd1e5.PNG)

**Comment by rviljoen** [comment]
@leandroalonso I believe this bug was introduced with commit https://github.com/Automattic/pocket-casts-ios/commit/42aa2754814640957063be31c9b5faadc56da509

It adds an SVG image named `close`, but `PlayerImages.xcassets` already contains a PNG image asset with the same name, which results in `ModalCloseButton` loading the incorrect one, then resulting in the rendering bug. Renaming the newly added SVG resolves the issue.

I assume the original close PNG is used elsewhere in the app as well, so this conflict may cause more issues. Not sure if you want to rename the newly added one, or update the code to make use of a single close icon.

**Comment by rviljoen** [comment]
@leandroalonso Bumping this to the top of your queue. May be a quick fix in between bigger tasks.

**Comment by leandroalonso** [comment]
Hey @rviljoen! Thanks for the ping.

This is a minor issue that affects a small portion of the users so I think it's a good candidate for a contributor to fix it and gain a bit of context of the code. :)

**Comment by rviljoen** [comment]
Thanks @leandroalonso! I'll take a shot at it. In terms of the following:

> I assume the original close PNG is used elsewhere in the app as well, so this conflict may cause more issues. Not sure if you want to rename the newly added one, or update the code to make use of a single close icon.

My thinking is to rename the newly added, conflicting icon. This would be the lowest risk and require the least amount of regression testing. Do you agree?

**Comment by leandroalonso** [comment]
@rviljoen absolutely! Plus this was used only on the End of Year feature which is now not available anymore.
