### ISSUE TITLE
Show episode artwork if available

### ISSUE THREAD

**Issue by glebd** [Automattic/pocket-casts-ios#595]
### Expected behavior

When displaying episode artwork, the embedded episode artwork is used if available, otherwise podcast artwork is used.

### Actual behavior

Podcast artwork is used even when episode artwork is available.

### Steps to reproduce the behavior

Subscribe to the Lions Led By Donkeys podcast, which has episode-specific artwork for each episode: https://podcasts.apple.com/gb/podcast/lions-led-by-donkeys-podcast/id1393845532

The listed episodes should have their custom episode-specific artwork instead of the podcast logo.

##### Tested on iPhone 8 Plus, iOS 16.1.2, Pocket Casts 7.27 (7.27.0.6)

**Comment by glebd** [comment]
It would also be very helpful if episode lists had episode artwork as item images.

**Comment by rviljoen** [comment]
I did some research into this and from what I can tell there is no embedded artwork in the MP3 for this specific podcast. There is, however, an `<itunes:image>` URL specified for each episode in the RSS feed under the `<item>` tag, which is the correct image to display:
https://feeds.soundcloud.com/users/soundcloud:users:457245963/sounds.rss
![image](https://user-images.githubusercontent.com/25402814/214683297-4ea6d76a-eda3-4748-be75-70389662d00d.png)

Current code caters for:
- Show artwork in the RSS (`<itunes:image>` under `<channel>`)
- Embedded artwork in downloaded file (if it exists and relevant setting enabled)

Apple documentation for these tags are available here: 
https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Since RSS processing is happening on the server, we'll need help to understand if this tag is already processed and available for us to sync at the episode level to the client. @geekygecko are you able to help or point me in the right direction, please?

**Comment by geekygecko** [comment]
@rviljoen thanks for having a look into this. We are making these episode images available from the server soon. The extra JSON also includes chapters that are embedded in the feed XML. I will post some more details once they are in production.

**Comment by manuelfgf** [comment]
> It would also be very helpful if episode lists had episode artwork as item images.

I would love to see this feature implemented as well.
