### ISSUE TITLE
Starred Episodes option missing when logged out

### ISSUE THREAD

**Issue by joashrajin** [Automattic/pocket-casts-ios#681]
### Expected behavior

When logged out, you should see the Starred Option as it works on Android

### Actual behavior

As soon as you log out, the Starred option disappears from the Profile Screen. This happens even if you have starred episodes. 

iOS vs Android:
<img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/216039463-989458f9-d821-48af-82f0-df8e1332817c.png"> <img width="48%" alt="image" src="https://user-images.githubusercontent.com/16253818/216039339-abff8431-abab-48dc-b46c-8d9c2d615113.png">

### Steps to reproduce the behavior

- Be logged into an account
- Go to Profile, and notice the 'Starred' option 
- Sign out of your account
- Notice the option is now gone

**Comment by rviljoen** [comment]
There is an explicit check to remove starred episodes from that screen, when the user is not logged in:
https://github.com/Automattic/pocket-casts-ios/blob/762da1073d68cb9a53c0b3f3cd026a4c6c58a31e/podcasts/ProfileViewController.swift#L471-L477

This code has been in place since the first open source submission. Maybe someone on the Pocket Casts team can see if there is more code or commit history in the pre-open source repo to explain why this check is in place?

Note: when looking at this, we should also consider bug https://github.com/Automattic/pocket-casts-ios/issues/653 which was already fixed. If starring episodes should indeed not be available for logged out users (as per the current code), then we will need to make it consistent throughout the app.
