### ISSUE TITLE
Clean FeatureFlag, Beta Features and GeneralSettingsViewController

### ISSUE THREAD

**Issue by yaelirub** [Automattic/pocket-casts-ios#920]
Clean FeatureFlag functionality, beta features and settings screen.
There are a bunch of beta features that are already in production, so we can remove their feature flag and beta.

**Comment by leandroalonso** [comment]
@yaelirub We're in sync! I created the same issue while working on #917: https://github.com/Automattic/pocket-casts-ios/issues/915

Which one shall we keep?

**Comment by yaelirub** [comment]
@leandroalonso, I copied your description here so we can keep this one :D

**Comment by emilylaguna** [comment]
I am going to close this issue since I ended up removing the old feature flags and the files that are no longer being used by them. 

We can track the new flags that need removal as separate issues like I did here:
- https://github.com/Automattic/pocket-casts-ios/issues/1304
- https://github.com/Automattic/pocket-casts-ios/issues/1305

### Flags Removed

- https://github.com/Automattic/pocket-casts-ios/pull/1283
- https://github.com/Automattic/pocket-casts-ios/pull/1282
- https://github.com/Automattic/pocket-casts-ios/pull/1281
- https://github.com/Automattic/pocket-casts-ios/pull/1280
- https://github.com/Automattic/pocket-casts-ios/pull/1279
- https://github.com/Automattic/pocket-casts-ios/pull/1278
- https://github.com/Automattic/pocket-casts-ios/pull/1277
- https://github.com/Automattic/pocket-casts-ios/pull/1276
- https://github.com/Automattic/pocket-casts-ios/pull/1275
- https://github.com/Automattic/pocket-casts-ios/pull/1274
- https://github.com/Automattic/pocket-casts-ios/pull/1273
- https://github.com/Automattic/pocket-casts-ios/pull/1271
- https://github.com/Automattic/pocket-casts-ios/pull/1270
- https://github.com/Automattic/pocket-casts-ios/pull/1266
